# -*- coding: utf-8 -*-
"""BTTuan1_LeDinhMinhQuang_2045240252.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15R_onZ0fblPWdB9_oQHO4ewJNK1qT7ni
"""

# Bai 1 Viết chương trình nhập vào 2 giá trị a, b và tính tổng, hiệu, tích thương của a và b.
a = (int)(input("Nhap vao gia tri a: "))
b = (int)(input("Nhap vao gia tri b: "))
phepcong = a + b
pheptru = a - b
phepnhan = a*b
phepchia=a/b
print("\n phep cong: ",phepcong)
print("\n phep tru: ",pheptru)
print("\n phep nhan: ",phepnhan)
print("\n phep chia: ", phepchia)

# Bai 2 Lấy các ký tự từ chỉ số 2 đến chỉ số 4 (llo) của chuỗi “Hello World”.
string = input ("\nNhap Chuoi: ")
print(string[2:5:])

# Bai 3 Xóa khoảng trắng thừa ở đầu và cuối chuỗi “ Hello World ”. Chuyển chuỗi sang dạng hoa và thường. Thay ký tự H thành ký tự J.
original_string = " Hello World "
print(f"Original string: '{original_string}'")

stripped_string = original_string.strip()
print(f"String after stripping whitespace: '{stripped_string}'")

uppercase_string = stripped_string.upper()
print(f"String in uppercase: '{uppercase_string}'")

lowercase_string = stripped_string.lower()
print(f"String in lowercase: '{lowercase_string}'")

replaced_string = stripped_string.replace('H', 'J')
print(f"String after replacing 'H' with 'J': '{replaced_string}'")

# Bai 4 In ra “Hello World!” nếu a lớn hơn b.
a1 = (int)(input("Nhap vao gia tri a: "))
b1 = (int)(input("Nhap vao gia tri b: "))
if a1>b1:
  print("Hello World")

#Bai 5 In ra “Yes” nếu a bằng b, ngược lại in “No”.
a2 = (int)(input("Nhap vao gia tri a: "))
b2 = (int)(input("Nhap vao gia tri b: "))
if a2 == b2:
  print("Yes")
else:
  print("No")

#Bai 6 In 1 nếu a bằng b, in 2 nếu a > b, in 3 nếu ngược lại.
a = (int)(input("Nhap vao gia tri a: "))
b = (int)(input("Nhap vao gia tri b: "))
if a == b: print(1)
elif a > b: print(2)
else: print(3)

#bai 7 In ra “Hello World!” nếu a bằng b và b bằng d.
a = (int)(input("Nhap vao gia tri a: "))
b = (int)(input("Nhap vao gia tri b: "))
if a == b & b == d:print("HelloWorld")

#Bai 8 In ra “Hello World!” nếu a bằng b hoặc c bằng d.
a = (int)(input("Nhap vao gia tri a: "))
b = (int)(input("Nhap vao gia tri b: "))
c = (int)(input("Nhap vao gia tri c: "))
d = (int)(input("Nhap vao gia tri d: "))
if a == b or c == d:print("HelloWorld")

#Bai 9
a = (int)(input("Nhap vao gia tri a: "))
b = (int)(input("Nhap vao gia tri b: "))
print('yes') if a > b else print('No')

#Bai 10
a = (int)(input("Nhap vao gia tri a: "))
b = (int)(input("Nhap vao gia tri b: "))
print('A') if a > b else print("=") if a == b else print('B')

#Bai 11
e = (int)(input("nhap vao n phan tu vao mang a: "))
import numpy as np
manga = np.random.rand(e)
mangb = []
for element in manga:
  if(element % 2 == 0):
    mangb.append(True)
  else:
    mangb.append(False)
newmangb = np.array(mangb)
print(manga)
print(newmangb)

#Bai 12
sum = 0
n = 999
for i in range(n):
  if i % 5 == 0 or i % 3 == 0:
    sum +=i


print("Tong cac so tu 0 den 999 ma la boi cua 5 hoac 3 la: ",sum)

#Bai 13
a = ([14, 12, 20, 6])
b = ([21, 12, 20, 6, 12, 5])
min = len(b) if len(a) > len(b) else len(a)
c = a if len(a) > len(b) else b
for i in range(min):
  c[i] = a[i] + b[i]

print(c)

#Bai 14
import numpy as np
m = (int)(input("Nhap vao m dong: "))
n = (int)(input("Nhap vao n cot: "))
#Cau a
manganew = np.random.rand(m,n)
print("mang a sau khi random: ",manganew)
#Cau b
k = (int)(input("nhap vao dong k ma ban muon: "))
k = manganew[k]
print("\nCac phan tu thuoc dong k: ",k)
#Cau c:
k1 = (int)(input("nhap vao cot k ma ban muon lay ra: "))
k1 = [row[k1] for row in manganew ]
print("\n cac phan tu thuoc cot k la: ", k1)
#Cau d: Tìm dòng có tổng lớn nhất
row_sums = np.sum(manganew, axis=1)
max_row_index = np.argmax(row_sums)
row_with_max_sum = manganew[max_row_index]
print("\nDong co tong lon nhat la:", row_with_max_sum)
print("Tong cua dong do la:", row_sums[max_row_index])
#cau e: Tìm cột có tích nhỏ nhất
#cau f: Xuất ra các phần tử thuộc dòng chẵn và cột lẻ trong a.
#cau g: Tính trung bình cộng các phần tử chẵn thuộc dòng lẻ của a.
#Cau h: Tính trung bình cộng các phần tử thuộc biên.
#cau i: Tính trung bình tích các phần tử không thuộc biên.

#Bai 15
class SinhVien:
  def __init__ (self, n):
    self.dic_SinhVien = {'maSV': [],
                         'hoTen': [],
                         'namsinh': [],
                         'diemTB': []
                        }
    for i in range(n):
      maSV = input(f"Nhap vao ma sinh vien thu {i+1}: ")
      hoTen = input(f"Nhap vao ho ten sinh vien thu {i+1}: ")
      namsinh = int(input(f"Nhap vao nam sinh sinh vien thu {i+1}: "))
      diemTB = float(input(f"Nhap vao diem trung binh sinh vien thu {i+1}: "))
      self.dic_SinhVien['maSV'].append(maSV)
      self.dic_SinhVien['hoTen'].append(hoTen)
      self.dic_SinhVien['namsinh'].append(namsinh)
      self.dic_SinhVien['diemTB'].append(diemTB)

sv_manager = SinhVien(2)
print(sv_manager.dic_SinhVien)

#c Viết hàm cho biết có bao sinh viên đủ điều kiện lên lớp, biết rằng sinh viên đủ điều kiện lên lớp khi điểm trung bình lớn hơn hoặc bằng 5.
def check_pass(dic_SinhVien):
  count = 0
  for i in range(len(dic_SinhVien['diemTB'])):
    if dic_SinhVien['diemTB'][i] >= 5:
      count += 1
  return count

print("so luong sinh vien du dieu kien len lop la: ",check_pass(sv_manager.dic_SinhVien))
#d Xuất các sinh viên đủ 20 tuổi.
def check_age(dic_SinhVien):
  for i in range(len(dic_SinhVien['namsinh'])):
    if 2026 - dic_SinhVien['namsinh'] >= 20:
      print ("Sinh co lon hon 20 tuoi la: ",check_age(sv_manager.dic_SinhVien['hoTen']))
    else:
      print ('khong co sinh vien nao tren 20 tuoi')

